const vegetables=[['tomato','الطماطم','🍅','4.80','↑ 8.2%','tomato'],['potato','البطاطس','🥔','3.60','↓ 4.1%','potato'],['carrot','الجزر','🥕','5.20','↑ 2.5%','carrot'],['onion','البصل','🧅','4.10','— ثابت','onion'],['pepper','الفلفل الأخضر','🫑','7.40','↓ 1.8%','pepper']];
const markets=[['س','سوق الجملة','الدار البيضاء','2.4 كم','4.20','green'],['م','سوق مديونة','مديونة','6.8 كم','4.60','orange'],['ب','سوق البرنوصي','الدار البيضاء','8.1 كم','5.10','purple'],['ق','سوق القريعة','الدار البيضاء','9.7 كم','5.30','green']];let route='onboarding',previous='home',slide=0,selected=vegetables[0];const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function renderVeg(q=''){let rows=vegetables.filter(v=>v[1].includes(q));$('#vegetables').innerHTML=rows.length?rows.map(v=>`<article class="veg" data-id="${v[0]}"><i class="${v[5]}">${v[2]}</i><span><b>${v[1]}</b><small>متوسط ${[6,8,5,7,4][vegetables.indexOf(v)]} أسواق</small></span><strong>${v[3]}<em class="${v[4][0]=='↓'?'down':''}">${v[4]}<br><small>درهم / كغ</small></em></strong><b class="arrow">‹</b></article>`).join(''):'<div class="empty">⌕<b>لم نجد هذه الخضرة</b><small>جرّب كلمة بحث مختلفة.</small></div>'}
function renderMarkets(){$('#markets').innerHTML=markets.map((m,i)=>`<article class="market"><i>${String(i+1).padStart(2,'0')}</i><mark class="${m[5]}">${m[0]}</mark><span><b>${m[1]} ${i===0?'<em>الأفضل</em>':''}</b><small>${m[2]} · ${m[3]} منك</small></span><strong>${m[4]}<small> درهم / كغ</small></strong></article>`).join('')}
function go(to){if(to!==route&&route!=='onboarding')previous=route==='onboarding'?'home':route;route=to;$$('.view').forEach(v=>v.classList.toggle('active',v.id===to));$('#nav').style.display=to==='onboarding'?'none':'flex';$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===to));if(to==='detail'){let [id,n,e,p,t,c]=selected;$('#detail-name').textContent=n;$('#detail-emoji').textContent=e;$('#detail-price').innerHTML=`${p} <small>درهم / كغ</small>`;$('#detail-trend').textContent=t}if(to==='home')renderVeg($('#search').value)}
function toast(text){let t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2400)}
function slideTo(n){slide=n;let a=[["اعرف أسعار<br><em>الخضر اليوم</em>","تابع مؤشر الأسعار في مدينتك واتخذ قرار الشراء بثقة، كل صباح."],["قارن الأسواق<br><em>حولك بسهولة</em>","اكتشف السوق الأقرب والأوفر، ووفر أكثر في كل مرة تشتري فيها."],["شارك سعرك<br><em>مع مجتمعك</em>","للبائعين والفلاحين: انشر أسعارك في ثوانٍ وساعد الآخرين على الاختيار."]][n];$("#intro-title").innerHTML=a[0];$("#intro-text").textContent=a[1];$$(".dots button").forEach((b,i)=>b.classList.toggle("active",i===n));$(".intro-next").innerHTML=n===2?"ابدأ الآن <b>←</b>":"التالي <b>←</b>";}
document.addEventListener('click',e=>{let goBtn=e.target.closest('[data-go]');if(goBtn){previous=route;go(goBtn.dataset.go);return}if(e.target.closest('[data-back]')){go(previous||'home');return}let v=e.target.closest('[data-id]');if(v){selected=vegetables.find(x=>x[0]===v.dataset.id);go('detail');return}let s=e.target.closest('[data-slide]');if(s){slideTo(+s.dataset.slide);return}if(e.target.closest('.intro-next')){slide<2?slideTo(slide+1):go('home');return}if(e.target.closest('#favorite')){let b=$('#favorite');b.textContent=b.textContent==='♡'?'♥':'♡';toast(b.textContent==='♥'?'تمت الإضافة إلى مفضلاتك':'تمت الإزالة من مفضلاتك');return}if(e.target.closest('[data-toast]'))toast(e.target.closest('[data-toast]').dataset.toast);if(e.target.closest('.chips button')){$$('.chips button').forEach(b=>b.classList.remove('selected'));e.target.closest('button').classList.add('selected');toast('تم تحديث التصنيف')}});
$('#search').addEventListener('input',e=>renderVeg(e.target.value));$('#price-form').addEventListener('submit',e=>{e.preventDefault();let p=e.target.elements.price.value;if(!p||+p<=0)return toast('أدخل سعراً صحيحاً أولاً');toast('تم نشر السعر بنجاح — شكراً لمساهمتك');e.target.reset()});renderVeg();renderMarkets();slideTo(0);go(location.hash.slice(1)||'onboarding');
